### ISSUE TITLE
Bug: Possible to replace any file when using `Original Name` Format

### ISSUE THREAD

**Issue by respektive** [dicedtomatoreal/typex#467]
### What happened?

When setting the Format to `Original Name` like in the image below, it is possible to replace any already uploaded file if they share the same name and file extension. 
![](https://pek.li/aP4tnJ.png)

Ideally there should be a check for already existing files. The upload could then be denied, or alternatively change the filename by appending a suffix or something like that.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by diced** [comment]
should be fixed in https://github.com/diced/zipline/commit/93cb9eec4c9435705fa37cffe99e9698e4509a5b
reopen if the issue happens again

**Comment by respektive** [comment]
Still happens on version 3.7.5 using the latest docker image. (also seems like i can't reopen the issue, only comment :thinking:)

**Comment by diced** [comment]
ok its actually fixed in this https://github.com/diced/zipline/commit/b39507b9a817b26cd518282ea3ae405dbf59487b

**Comment by mptpro** [comment]
Sorry for the late comment... but would it possible to actually replace the file with the newly-uploaded one, and keep the URL the same?

**Comment by diced** [comment]
no that would reverse the bug.. something in the future could be added where a file can be replaced in-place prolly.
