### ISSUE TITLE
Bug: Multiple issues with the iOS Shortcuts script when interfacing with v4.

### ISSUE THREAD

**Issue by barretgoat** [dicedtomatoreal/typex#745]
### What happened?

I am on iOS 18.2 and following the iOS Shortcut guide described here: https://zipline.diced.sh/docs/guides/uploaders/ios-shortcuts

The shortcut successfully uploads pictures and files, but the URL is not copied to the clipboard.

When uploading a picture from the gallery or miscellaneous files both through the shortcut's menu as well as the sharing menu, the string that gets copied to the clipboard looks like this:
`{"id":"longstringofnumbersandletters","type":"image\/jpeg","url":"https:\/\/domainname.tld\/6yCZ84.jpeg","removedGps":true}`

When uploading specifically a .pdf file specifically through the sharing menu, the shortcut's default dialogue opens instead:
![Image](https://github.com/user-attachments/assets/81036178-5408-4ad6-b3bc-80a4648924bb)

When shortening a URL, I get the following error displayed by the shortcut:
![Image](https://github.com/user-attachments/assets/18c14d33-23f2-41db-b1a7-977da73a09be)

For the URL shortener, the error occurs in this specific block:
![Image](https://github.com/user-attachments/assets/0f78500d-3f3e-4dd3-947e-003c7dca7609)

### Version

Latest v4 release (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell

```

### Browser Logs

```shell

```

**Comment by RagnarLothbrok-Odin** [comment]
The way data is returned has changed, a couple of others requested this update in the Discord but afaik diced doesn’t have iOS?
Anyway, I fixed it here:

https://www.icloud.com/shortcuts/f297e446fd1346beaa52636a865349eb

**Comment by barretgoat** [comment]
> The way data is returned has changed, a couple of others requested this update in the Discord but afaik diced doesn’t have iOS? Anyway, I fixed it here:
> 
> https://www.icloud.com/shortcuts/f297e446fd1346beaa52636a865349eb

That mostly works! The .pdf bug remains (when using the sharing menu on an open pdf file), but that's very far from critical. Thank you for the link.
