### ISSUE TITLE
Bug: Animated GIF becomes a static image when compression is enabled (WebP)

### ISSUE THREAD

**Issue by Jade9nan** [dicedtomatoreal/typex#926]
### Bug description

When the compression option is enabled in Zipline, uploading an animated GIF results in a static WebP image.
All animation frames are lost after compression, even though [WebP does support animation](https://github.com/lovell/sharp/issues/1823#issuecomment-1575045683), and `sharp` also supports converting animated GIF → animated WebP.

So the output should remain animated, but currently it becomes a single-frame static image.

### How is Zipline being run?

On docker (docker, docker compose, etc.)

### Zipline Version

4.3.2 (commit 2ad10e9)

### Steps to Reproduce

1. Enable Compression in Zipline settings.
2. Upload an animated GIF (any multi-frame GIF works).
3. Download or view the processed file.
4. The output becomes a static WebP instead of an animated WebP.

**Comment by diced** [comment]
fixed ^

**Comment by thelastfantasy** [comment]
@diced I've tested the latest trunk version (including commit 3fc8b044), but animated GIF to animated WebP
  conversion is still not working.

  ### Test Results

  Uploaded an animated GIF (configured for 85% compression to WebP):

  **File link:** https://taosaka.com/view/illegal-faint-alpineroadguidetigerbeetle.webp
  **Raw file:** https://taosaka.com/raw/illegal-faint-alpineroadguidetigerbeetle.webp

  ### Technical Analysis

  #### 1. File Format Check
  ```bash
  $ file /tmp/actual_image.webp
  /tmp/actual_image.webp: GIF image data, version 89a, 800 x 746
```

  The file is still in GIF format, not WebP. The animated GIF was not converted to animated WebP.

  2. The Problem

  The animated GIF remains as GIF instead of being converted to animated WebP. The server serves GIF files with
  .webp extension and Content-Type: image/webp, but the actual content is still GIF format.

**Comment by diced** [comment]
@thelastfantasy thanks for reporting that, but please don't use ai for your comments as it just wastes time for me.

**Comment by thelastfantasy** [comment]
@diced Another issue with the animated conversion: commit 3fc8b044bb295eec3da7fe541ce908f0c69bd801 includes
  `.avif` in the animated formats detection, but when I try to upload an animated AVIF, it fails with response:
```
  {"error":"Internal Server Error","statusCode":500,"message":"Input file contains unsupported image format"}
```
  Test file (animated AVIF): https://colinbendell.github.io/webperf/animated-gif-decode/avif.html (second image)

**Comment by diced** [comment]
>  in the animated formats detection, but when I try to upload an animated AVIF, it fails with response:

unfortunately sharp doesnt support avif image sequences so i'm not gonna really do anything ab this except for handle this error in a better way (just passthrough without animation if it errors out), if you really need this you can build libvips and provide the binary and set the `SHARP_FORCE_GLOBAL_LIBVIPS` environment variable.

**Comment by thelastfantasy** [comment]
> unfortunately sharp doesnt support avif image sequences so i'm not gonna really do anything ab this except for handle this error in a better way (just passthrough without animation if it errors out), if you really need this you can build libvips and provide the binary and set the `SHARP_FORCE_GLOBAL_LIBVIPS` environment variable.

In that case, I suggest that if the environment variable is not present, AVIF files should be treated as binary uploads (similar to how I can upload ZIP and APK files) rather than being rejected with an error.

**Comment by Venipa** [comment]
still happening with gif's, uploaded it through sharex as a gif file, file compression set to 94 through header in custom uploader config, static jpg returned with every frame stacked vertically.
removing the compression header resolved it.
